# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(b'1', b'\xe8\x8d\x89\xe7\xa8\xbf'), (b'2', b'\xe5\x8f\x91\xe5\xb8\x83')], default=b'\xe8\x8d\x89\xe7\xa8\xbf', max_length=10),
        ),
    ]
